### ISSUE TITLE
feedback on new command

### ISSUE THREAD

**Issue by HERRKIN** [terminalvelocity/seeds.js#56] opened 2015-06-27 00:39 UTC
it takes too long and I dont know what it is doing or if it is still working or its frozen, at least I think it should have a spinner like npm uses for the installs, maybe you can log 'installing api' then 'installing frontend' something like that but definitely it needs some indicator .

**Comment by jhliberty** [comment] 2015-06-28 08:30
I agree, I am unhappy with the current state of the new command because it is so slow. I moved the sails and ember setups into their own packages and they install/setup apps in ~1 sec, however due to the fact that npm currently always ignore node modules, the new command ends up calling npm install three times and npm is just horribly, horribly slow.

I'm currently researching the best solution to this problem. I'm open to suggestions if anyone has an idea.

As always, thanks for the feedback @HERRKIN - I really appreciate it! =D

**Comment by IanVS** [comment] 2015-06-29 19:00
How about checking dependencies into the seeds repo and then copying them over along with the templates instead of npm installing?

**Comment by austinpray** [comment] 2015-06-29 19:20
>checking dependencies into the seeds repo and then copying them over along with the templates instead of npm installing?

Yeah this is what most of the yeoman projects do

**Comment by IanVS** [comment] 2015-06-29 20:53
If I'm not mistaken, the issue is that generators need to also be run to set up ember and sails, it's not just a simple `npm install`.  So, sails and ember have to be npm installed from seeds, then `ember new` and `sails new` have to be run, each of which also perform an npm install.

**Comment by jhliberty** [comment] 2015-07-01 07:51
@IanVS By default node_modules are ignored by npm. Plus managing this in repo would be a pita. It's certainly an option though a painful one because I think we would have to rename ever folder named node_modules to something else and then recursively rename them back when we generate a new one.

As of 2.0.0 Seeds doesn't run ember/sails new any more. It uses the sails generator to actually copy over the full, working templates but requires an npm install to be useful. #57 is an attempt to just add all of the deps needed in the top level package.json, npm install one time and then copy the deps to the proper app files. I need some feedback on whether or not this is faster than the three npm installs or if its about the same.

If that doesn't work I'm not sure there is a good option here other than just adding an indicator and a note that it could take some time on slower machines.

**Comment by jhliberty** [comment] 2015-07-01 07:53
I'm also inclined to follow @jamemackson's advice and just not worry about it since the new command is invoked once and may not be an issue worth prioritizing over other features.

**Comment by jhliberty** [comment] 2015-07-01 07:56
Another solution could be to add all of these deps to the seeds package itself and frontload the deps on the first install of seeds. This would slow the seeds install initially but speed up subsequent new commands.

**Comment by IanVS** [comment] 2015-07-03 14:37
Yes, loading them with the seeds install was my other thought.  The only downside I see is that maybe you need a `seeds update` command to bring the those packages up to date if it's been a while since seeds was installed (or tell people to install seeds and reinstall, but that seems clunky).

**Comment by IanVS** [comment] 2015-07-04 00:27
Yes, loading them with the seeds install was my other thought.  The only downside I see is that maybe you need a `seeds update` command to bring the those packages up to date if it's been a while since seeds was installed (or tell people to install seeds and reinstall, but that seems clunky).

**Comment by IanVS** [comment] 2015-07-08 04:16
Hm, I don't think I meant to close this issue.

**Comment by jhliberty** [comment] 2015-07-15 09:39
I was curious about that lol

**Comment by IanVS** [comment] 2015-07-15 12:31
That's the risk of using GitHub on my phone.  I get pocket issue closes apparently...

**Comment by IanVS** [comment] 2015-07-17 01:20
Ember-cli [plans](https://github.com/ember-cli/ember-cli/issues/3380) to implement a `ember new --local` option to use local cache instead of downloading from the internet.  That may help speed things up once it lands.

**Comment by HERRKIN** [comment] 2015-07-17 01:30
I would love that, I also noticed sublime text works weird when I a folder
with multiple ember projects opened. too many files

2015-07-16 20:50 GMT-04:30 Ian VanSchooten <notifications@github.com>:

**Comment by IanVS** [comment] 2015-07-17 01:45
For sublime text, have you edited your user preferences and added `dist`, `tmp`, and `node_modules`? I like to use

```
"folder_exclude_patterns":
	[
		".git",
		"dist",
		"tmp/*",
		"node_modules/*"
	]
```

**Comment by HERRKIN** [comment] 2015-07-17 01:46
what is that for?

**Comment by IanVS** [comment] 2015-07-17 01:48
It prevents Sublime from trying to index all the files in those folders.

**Comment by HERRKIN** [comment] 2015-07-17 01:49
great thanks. I didnt know that.

**Closed** 2016-08-03 21:29 UTC
Labels: future
